enable_cache: False
extra:
  tags: zenml-projects
settings:
  docker:
    required_integrations:
      - mlflow
steps:
  process_train_model:
    experiment_tracker: mlflow_experiment_tracker
  process_evaluate:
    experiment_tracker: mlflow_experiment_tracker
