name: Run Training Pipeline

on: [push, pull_request]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install ZenML dependencies and setup stack
      run: |
        pip install zenml
        zenml init
        pip install "zenml[server]"
        zenml integration install mlflow
        zenml stack register my_stack_name -d mlflow_model_deployer -e mlflow_experiment_tracker -a default -o default -r mlflow_model_register
        zenml stack set my_stack_name

    - name: Run Training Script
      run: python run_training_pipeline.py
